version: '3.9'

services:
  web:
    build: .
    ports:
      - "5001:5001"
    environment:
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 5001
      FLASK_DEBUG: 0
      FLASK_ENV: production
      DATABASE_URL: 'sqlite:///data.db'
      HTTP_SERVER_URL: 'http://127.0.0.1:5001'
      LEVEL: 'DEBUG'
    volumes:
      - .:/app
    command: >
      uwsgi --http 0.0.0.0:5001
             --module run:app
             --master
             --processes 4
             --threads 2
             --vacuum
             --die-on-term